/********************************************************************************
** Form generated from reading UI file 'Gui.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GUI_H
#define UI_GUI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Gui
{
public:
    QWidget *centralWidget;
    QGroupBox *groupBox;
    QComboBox *comboBox;
    QLineEdit *lineEdit;
    QLabel *label;
    QLabel *label_2;
    QPushButton *pushButton;
    QLabel *label_3;
    QLineEdit *lineEdit_2;
    QCheckBox *checkBox;
    QGroupBox *groupBox_8;
    QGroupBox *groupBox_9;
    QLCDNumber *lcdNumber;
    QLabel *label_17;
    QLabel *label_18;
    QLCDNumber *lcdNumber_2;
    QLabel *label_19;
    QLCDNumber *lcdNumber_3;
    QLabel *label_20;
    QLCDNumber *lcdNumber_4;
    QLabel *label_21;
    QLCDNumber *lcdNumber_5;
    QLabel *label_22;
    QLCDNumber *lcdNumber_6;
    QLabel *label_23;
    QLCDNumber *lcdNumber_7;
    QLCDNumber *lcdNumber_8;
    QLabel *label_24;
    QLabel *label_26;
    QLCDNumber *lcdNumber_10;
    QGroupBox *groupBox_10;
    QLCDNumber *lcdNumber_17;
    QLabel *label_33;
    QLabel *label_34;
    QLCDNumber *lcdNumber_18;
    QLabel *label_35;
    QLCDNumber *lcdNumber_19;
    QLabel *label_36;
    QLCDNumber *lcdNumber_20;
    QLabel *label_37;
    QLCDNumber *lcdNumber_21;
    QLabel *label_38;
    QLCDNumber *lcdNumber_22;
    QLabel *label_39;
    QLCDNumber *lcdNumber_23;
    QLCDNumber *lcdNumber_24;
    QLabel *label_40;
    QLabel *label_27;
    QLCDNumber *lcdNumber_11;
    QGroupBox *groupBox_2;
    QComboBox *comboBox_2;
    QLabel *label_4;
    QLabel *label_5;
    QPushButton *pushButton_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLabel *label_12;
    QCheckBox *checkBox_2;
    QGroupBox *groupBox_11;
    QGroupBox *groupBox_12;
    QLCDNumber *lcdNumber_25;
    QLabel *label_41;
    QLabel *label_42;
    QLCDNumber *lcdNumber_26;
    QLabel *label_43;
    QLCDNumber *lcdNumber_27;
    QLabel *label_44;
    QLCDNumber *lcdNumber_28;
    QLabel *label_45;
    QLCDNumber *lcdNumber_29;
    QLabel *label_46;
    QLCDNumber *lcdNumber_30;
    QLabel *label_47;
    QLCDNumber *lcdNumber_31;
    QLCDNumber *lcdNumber_32;
    QLabel *label_48;
    QLabel *label_28;
    QLCDNumber *lcdNumber_12;
    QGroupBox *groupBox_13;
    QLCDNumber *lcdNumber_33;
    QLabel *label_49;
    QLabel *label_50;
    QLCDNumber *lcdNumber_34;
    QLabel *label_51;
    QLCDNumber *lcdNumber_35;
    QLabel *label_52;
    QLCDNumber *lcdNumber_36;
    QLabel *label_53;
    QLCDNumber *lcdNumber_37;
    QLabel *label_54;
    QLCDNumber *lcdNumber_38;
    QLabel *label_55;
    QLCDNumber *lcdNumber_39;
    QLCDNumber *lcdNumber_40;
    QLabel *label_56;
    QLabel *label_29;
    QLCDNumber *lcdNumber_13;
    QGroupBox *groupBox_4;
    QListView *listView;
    QSpinBox *spinBox;
    QLabel *label_7;
    QPushButton *pushButton_7;
    QGroupBox *groupBox_5;
    QListView *listView_2;
    QPushButton *pushButton_8;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QComboBox *comboBox_3;
    QLabel *label_8;
    QLabel *label_10;
    QLabel *label_11;
    QPushButton *pushButton_9;
    QLineEdit *lineEdit_6;
    QLabel *label_13;
    QGroupBox *groupBox_6;
    QLabel *label_6;
    QLineEdit *lineEdit_9;
    QPushButton *pushButton_10;
    QGroupBox *groupBox_7;
    QListView *listView_3;
    QLabel *label_9;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QSpinBox *spinBox_2;
    QSpinBox *spinBox_4;
    QSpinBox *spinBox_5;
    QSpinBox *spinBox_6;
    QLabel *label_25;
    QLCDNumber *lcdNumber_9;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QGroupBox *groupBox_14;
    QLineEdit *lineEdit_5;
    QPushButton *pushButton_6;
    QLabel *label_57;

    void setupUi(QMainWindow *Gui)
    {
        if (Gui->objectName().isEmpty())
            Gui->setObjectName(QStringLiteral("Gui"));
        Gui->resize(1242, 943);
        centralWidget = new QWidget(Gui);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(0, 0, 331, 441));
        groupBox->setAlignment(Qt::AlignCenter);
        groupBox->setFlat(false);
        comboBox = new QComboBox(groupBox);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(100, 30, 201, 23));
        lineEdit = new QLineEdit(groupBox);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(100, 60, 141, 23));
        lineEdit->setAlignment(Qt::AlignCenter);
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 30, 67, 17));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 60, 71, 20));
        pushButton = new QPushButton(groupBox);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(190, 100, 91, 27));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(250, 60, 16, 21));
        lineEdit_2 = new QLineEdit(groupBox);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(270, 60, 31, 23));
        lineEdit_2->setAlignment(Qt::AlignCenter);
        checkBox = new QCheckBox(groupBox);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(40, 100, 111, 31));
        groupBox_8 = new QGroupBox(groupBox);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(0, 140, 331, 301));
        groupBox_8->setAlignment(Qt::AlignCenter);
        groupBox_8->setFlat(false);
        groupBox_9 = new QGroupBox(groupBox_8);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(0, 20, 161, 281));
        groupBox_9->setAlignment(Qt::AlignCenter);
        lcdNumber = new QLCDNumber(groupBox_9);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(100, 20, 64, 23));
        lcdNumber->setFrameShape(QFrame::NoFrame);
        lcdNumber->setSegmentStyle(QLCDNumber::Flat);
        label_17 = new QLabel(groupBox_9);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 20, 81, 21));
        label_18 = new QLabel(groupBox_9);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 50, 101, 21));
        lcdNumber_2 = new QLCDNumber(groupBox_9);
        lcdNumber_2->setObjectName(QStringLiteral("lcdNumber_2"));
        lcdNumber_2->setGeometry(QRect(100, 50, 64, 23));
        lcdNumber_2->setFrameShape(QFrame::NoFrame);
        lcdNumber_2->setSegmentStyle(QLCDNumber::Flat);
        label_19 = new QLabel(groupBox_9);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 110, 81, 21));
        lcdNumber_3 = new QLCDNumber(groupBox_9);
        lcdNumber_3->setObjectName(QStringLiteral("lcdNumber_3"));
        lcdNumber_3->setGeometry(QRect(100, 110, 64, 23));
        lcdNumber_3->setFrameShape(QFrame::NoFrame);
        lcdNumber_3->setSegmentStyle(QLCDNumber::Flat);
        label_20 = new QLabel(groupBox_9);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 140, 101, 21));
        lcdNumber_4 = new QLCDNumber(groupBox_9);
        lcdNumber_4->setObjectName(QStringLiteral("lcdNumber_4"));
        lcdNumber_4->setGeometry(QRect(100, 140, 64, 23));
        lcdNumber_4->setFrameShape(QFrame::NoFrame);
        lcdNumber_4->setSegmentStyle(QLCDNumber::Flat);
        label_21 = new QLabel(groupBox_9);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 201, 81, 21));
        lcdNumber_5 = new QLCDNumber(groupBox_9);
        lcdNumber_5->setObjectName(QStringLiteral("lcdNumber_5"));
        lcdNumber_5->setGeometry(QRect(100, 170, 64, 23));
        lcdNumber_5->setFrameShape(QFrame::NoFrame);
        lcdNumber_5->setSegmentStyle(QLCDNumber::Flat);
        label_22 = new QLabel(groupBox_9);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 230, 91, 21));
        lcdNumber_6 = new QLCDNumber(groupBox_9);
        lcdNumber_6->setObjectName(QStringLiteral("lcdNumber_6"));
        lcdNumber_6->setGeometry(QRect(100, 200, 64, 23));
        lcdNumber_6->setFrameShape(QFrame::NoFrame);
        lcdNumber_6->setSegmentStyle(QLCDNumber::Flat);
        label_23 = new QLabel(groupBox_9);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 260, 91, 21));
        lcdNumber_7 = new QLCDNumber(groupBox_9);
        lcdNumber_7->setObjectName(QStringLiteral("lcdNumber_7"));
        lcdNumber_7->setGeometry(QRect(100, 230, 64, 23));
        lcdNumber_7->setFrameShape(QFrame::NoFrame);
        lcdNumber_7->setSegmentStyle(QLCDNumber::Flat);
        lcdNumber_8 = new QLCDNumber(groupBox_9);
        lcdNumber_8->setObjectName(QStringLiteral("lcdNumber_8"));
        lcdNumber_8->setGeometry(QRect(100, 260, 64, 23));
        lcdNumber_8->setFrameShape(QFrame::NoFrame);
        lcdNumber_8->setSegmentStyle(QLCDNumber::Flat);
        label_24 = new QLabel(groupBox_9);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 171, 81, 21));
        label_26 = new QLabel(groupBox_9);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 80, 81, 17));
        lcdNumber_10 = new QLCDNumber(groupBox_9);
        lcdNumber_10->setObjectName(QStringLiteral("lcdNumber_10"));
        lcdNumber_10->setGeometry(QRect(100, 80, 64, 23));
        lcdNumber_10->setFrameShape(QFrame::NoFrame);
        lcdNumber_10->setFrameShadow(QFrame::Plain);
        lcdNumber_10->setSegmentStyle(QLCDNumber::Flat);
        groupBox_10 = new QGroupBox(groupBox_8);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(170, 20, 161, 281));
        groupBox_10->setAlignment(Qt::AlignCenter);
        lcdNumber_17 = new QLCDNumber(groupBox_10);
        lcdNumber_17->setObjectName(QStringLiteral("lcdNumber_17"));
        lcdNumber_17->setGeometry(QRect(100, 20, 64, 23));
        lcdNumber_17->setFrameShape(QFrame::NoFrame);
        lcdNumber_17->setSegmentStyle(QLCDNumber::Flat);
        label_33 = new QLabel(groupBox_10);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 20, 81, 21));
        label_34 = new QLabel(groupBox_10);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 50, 91, 21));
        lcdNumber_18 = new QLCDNumber(groupBox_10);
        lcdNumber_18->setObjectName(QStringLiteral("lcdNumber_18"));
        lcdNumber_18->setGeometry(QRect(100, 50, 64, 23));
        lcdNumber_18->setFrameShape(QFrame::NoFrame);
        lcdNumber_18->setSegmentStyle(QLCDNumber::Flat);
        label_35 = new QLabel(groupBox_10);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 110, 81, 21));
        lcdNumber_19 = new QLCDNumber(groupBox_10);
        lcdNumber_19->setObjectName(QStringLiteral("lcdNumber_19"));
        lcdNumber_19->setGeometry(QRect(100, 110, 64, 23));
        lcdNumber_19->setFrameShape(QFrame::NoFrame);
        lcdNumber_19->setSegmentStyle(QLCDNumber::Flat);
        label_36 = new QLabel(groupBox_10);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 140, 101, 21));
        lcdNumber_20 = new QLCDNumber(groupBox_10);
        lcdNumber_20->setObjectName(QStringLiteral("lcdNumber_20"));
        lcdNumber_20->setGeometry(QRect(100, 140, 64, 23));
        lcdNumber_20->setFrameShape(QFrame::NoFrame);
        lcdNumber_20->setSegmentStyle(QLCDNumber::Flat);
        label_37 = new QLabel(groupBox_10);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 201, 81, 21));
        lcdNumber_21 = new QLCDNumber(groupBox_10);
        lcdNumber_21->setObjectName(QStringLiteral("lcdNumber_21"));
        lcdNumber_21->setGeometry(QRect(100, 170, 64, 23));
        lcdNumber_21->setFrameShape(QFrame::NoFrame);
        lcdNumber_21->setSegmentStyle(QLCDNumber::Flat);
        label_38 = new QLabel(groupBox_10);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(10, 230, 91, 21));
        lcdNumber_22 = new QLCDNumber(groupBox_10);
        lcdNumber_22->setObjectName(QStringLiteral("lcdNumber_22"));
        lcdNumber_22->setGeometry(QRect(100, 200, 64, 23));
        lcdNumber_22->setFrameShape(QFrame::NoFrame);
        lcdNumber_22->setSegmentStyle(QLCDNumber::Flat);
        label_39 = new QLabel(groupBox_10);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(10, 260, 91, 21));
        lcdNumber_23 = new QLCDNumber(groupBox_10);
        lcdNumber_23->setObjectName(QStringLiteral("lcdNumber_23"));
        lcdNumber_23->setGeometry(QRect(100, 230, 64, 23));
        lcdNumber_23->setFrameShape(QFrame::NoFrame);
        lcdNumber_23->setSegmentStyle(QLCDNumber::Flat);
        lcdNumber_24 = new QLCDNumber(groupBox_10);
        lcdNumber_24->setObjectName(QStringLiteral("lcdNumber_24"));
        lcdNumber_24->setGeometry(QRect(100, 260, 64, 23));
        lcdNumber_24->setFrameShape(QFrame::NoFrame);
        lcdNumber_24->setSegmentStyle(QLCDNumber::Flat);
        label_40 = new QLabel(groupBox_10);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(10, 171, 81, 21));
        label_27 = new QLabel(groupBox_10);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 80, 81, 17));
        lcdNumber_11 = new QLCDNumber(groupBox_10);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(100, 80, 64, 23));
        lcdNumber_11->setFrameShape(QFrame::NoFrame);
        lcdNumber_11->setFrameShadow(QFrame::Plain);
        lcdNumber_11->setSegmentStyle(QLCDNumber::Flat);
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(330, 0, 331, 441));
        groupBox_2->setAlignment(Qt::AlignCenter);
        comboBox_2 = new QComboBox(groupBox_2);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(100, 30, 201, 23));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 30, 67, 17));
        label_5 = new QLabel(groupBox_2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 60, 71, 20));
        pushButton_2 = new QPushButton(groupBox_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(190, 100, 91, 27));
        lineEdit_3 = new QLineEdit(groupBox_2);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(100, 60, 141, 23));
        lineEdit_3->setAlignment(Qt::AlignCenter);
        lineEdit_4 = new QLineEdit(groupBox_2);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(270, 60, 31, 23));
        lineEdit_4->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(250, 60, 16, 21));
        checkBox_2 = new QCheckBox(groupBox_2);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setGeometry(QRect(40, 100, 111, 31));
        groupBox_11 = new QGroupBox(groupBox_2);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setGeometry(QRect(0, 140, 331, 301));
        groupBox_11->setAlignment(Qt::AlignCenter);
        groupBox_11->setFlat(false);
        groupBox_12 = new QGroupBox(groupBox_11);
        groupBox_12->setObjectName(QStringLiteral("groupBox_12"));
        groupBox_12->setGeometry(QRect(0, 20, 161, 281));
        groupBox_12->setAlignment(Qt::AlignCenter);
        lcdNumber_25 = new QLCDNumber(groupBox_12);
        lcdNumber_25->setObjectName(QStringLiteral("lcdNumber_25"));
        lcdNumber_25->setGeometry(QRect(100, 20, 64, 23));
        lcdNumber_25->setFrameShape(QFrame::NoFrame);
        lcdNumber_25->setSegmentStyle(QLCDNumber::Flat);
        label_41 = new QLabel(groupBox_12);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(10, 20, 81, 21));
        label_42 = new QLabel(groupBox_12);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(10, 50, 91, 21));
        lcdNumber_26 = new QLCDNumber(groupBox_12);
        lcdNumber_26->setObjectName(QStringLiteral("lcdNumber_26"));
        lcdNumber_26->setGeometry(QRect(100, 50, 64, 23));
        lcdNumber_26->setFrameShape(QFrame::NoFrame);
        lcdNumber_26->setSegmentStyle(QLCDNumber::Flat);
        label_43 = new QLabel(groupBox_12);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(10, 110, 81, 21));
        lcdNumber_27 = new QLCDNumber(groupBox_12);
        lcdNumber_27->setObjectName(QStringLiteral("lcdNumber_27"));
        lcdNumber_27->setGeometry(QRect(100, 110, 64, 23));
        lcdNumber_27->setFrameShape(QFrame::NoFrame);
        lcdNumber_27->setSegmentStyle(QLCDNumber::Flat);
        label_44 = new QLabel(groupBox_12);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(10, 140, 101, 21));
        lcdNumber_28 = new QLCDNumber(groupBox_12);
        lcdNumber_28->setObjectName(QStringLiteral("lcdNumber_28"));
        lcdNumber_28->setGeometry(QRect(100, 140, 64, 23));
        lcdNumber_28->setFrameShape(QFrame::NoFrame);
        lcdNumber_28->setSegmentStyle(QLCDNumber::Flat);
        label_45 = new QLabel(groupBox_12);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 200, 81, 21));
        lcdNumber_29 = new QLCDNumber(groupBox_12);
        lcdNumber_29->setObjectName(QStringLiteral("lcdNumber_29"));
        lcdNumber_29->setGeometry(QRect(100, 170, 64, 23));
        lcdNumber_29->setFrameShape(QFrame::NoFrame);
        lcdNumber_29->setSegmentStyle(QLCDNumber::Flat);
        label_46 = new QLabel(groupBox_12);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(10, 230, 91, 21));
        lcdNumber_30 = new QLCDNumber(groupBox_12);
        lcdNumber_30->setObjectName(QStringLiteral("lcdNumber_30"));
        lcdNumber_30->setGeometry(QRect(100, 200, 64, 23));
        lcdNumber_30->setFrameShape(QFrame::NoFrame);
        lcdNumber_30->setSegmentStyle(QLCDNumber::Flat);
        label_47 = new QLabel(groupBox_12);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(10, 260, 91, 21));
        lcdNumber_31 = new QLCDNumber(groupBox_12);
        lcdNumber_31->setObjectName(QStringLiteral("lcdNumber_31"));
        lcdNumber_31->setGeometry(QRect(100, 230, 64, 23));
        lcdNumber_31->setFrameShape(QFrame::NoFrame);
        lcdNumber_31->setSegmentStyle(QLCDNumber::Flat);
        lcdNumber_32 = new QLCDNumber(groupBox_12);
        lcdNumber_32->setObjectName(QStringLiteral("lcdNumber_32"));
        lcdNumber_32->setGeometry(QRect(100, 260, 64, 23));
        lcdNumber_32->setFrameShape(QFrame::NoFrame);
        lcdNumber_32->setSegmentStyle(QLCDNumber::Flat);
        label_48 = new QLabel(groupBox_12);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(10, 170, 81, 21));
        label_28 = new QLabel(groupBox_12);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 80, 81, 17));
        lcdNumber_12 = new QLCDNumber(groupBox_12);
        lcdNumber_12->setObjectName(QStringLiteral("lcdNumber_12"));
        lcdNumber_12->setGeometry(QRect(100, 80, 64, 23));
        lcdNumber_12->setFrameShape(QFrame::NoFrame);
        lcdNumber_12->setFrameShadow(QFrame::Plain);
        lcdNumber_12->setSegmentStyle(QLCDNumber::Flat);
        groupBox_13 = new QGroupBox(groupBox_11);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(170, 20, 161, 281));
        groupBox_13->setAlignment(Qt::AlignCenter);
        lcdNumber_33 = new QLCDNumber(groupBox_13);
        lcdNumber_33->setObjectName(QStringLiteral("lcdNumber_33"));
        lcdNumber_33->setGeometry(QRect(100, 20, 64, 23));
        lcdNumber_33->setFrameShape(QFrame::NoFrame);
        lcdNumber_33->setSegmentStyle(QLCDNumber::Flat);
        label_49 = new QLabel(groupBox_13);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(10, 20, 81, 21));
        label_50 = new QLabel(groupBox_13);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(10, 50, 101, 21));
        lcdNumber_34 = new QLCDNumber(groupBox_13);
        lcdNumber_34->setObjectName(QStringLiteral("lcdNumber_34"));
        lcdNumber_34->setGeometry(QRect(100, 50, 64, 23));
        lcdNumber_34->setFrameShape(QFrame::NoFrame);
        lcdNumber_34->setSegmentStyle(QLCDNumber::Flat);
        label_51 = new QLabel(groupBox_13);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(10, 110, 81, 21));
        lcdNumber_35 = new QLCDNumber(groupBox_13);
        lcdNumber_35->setObjectName(QStringLiteral("lcdNumber_35"));
        lcdNumber_35->setGeometry(QRect(100, 110, 64, 23));
        lcdNumber_35->setFrameShape(QFrame::NoFrame);
        lcdNumber_35->setSegmentStyle(QLCDNumber::Flat);
        label_52 = new QLabel(groupBox_13);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(10, 140, 101, 21));
        lcdNumber_36 = new QLCDNumber(groupBox_13);
        lcdNumber_36->setObjectName(QStringLiteral("lcdNumber_36"));
        lcdNumber_36->setGeometry(QRect(100, 140, 64, 23));
        lcdNumber_36->setFrameShape(QFrame::NoFrame);
        lcdNumber_36->setSegmentStyle(QLCDNumber::Flat);
        label_53 = new QLabel(groupBox_13);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(10, 201, 81, 21));
        lcdNumber_37 = new QLCDNumber(groupBox_13);
        lcdNumber_37->setObjectName(QStringLiteral("lcdNumber_37"));
        lcdNumber_37->setGeometry(QRect(100, 170, 64, 23));
        lcdNumber_37->setFrameShape(QFrame::NoFrame);
        lcdNumber_37->setSegmentStyle(QLCDNumber::Flat);
        label_54 = new QLabel(groupBox_13);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(10, 230, 91, 21));
        lcdNumber_38 = new QLCDNumber(groupBox_13);
        lcdNumber_38->setObjectName(QStringLiteral("lcdNumber_38"));
        lcdNumber_38->setGeometry(QRect(100, 200, 64, 23));
        lcdNumber_38->setFrameShape(QFrame::NoFrame);
        lcdNumber_38->setSegmentStyle(QLCDNumber::Flat);
        label_55 = new QLabel(groupBox_13);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(10, 260, 91, 21));
        lcdNumber_39 = new QLCDNumber(groupBox_13);
        lcdNumber_39->setObjectName(QStringLiteral("lcdNumber_39"));
        lcdNumber_39->setGeometry(QRect(100, 230, 64, 23));
        lcdNumber_39->setFrameShape(QFrame::NoFrame);
        lcdNumber_39->setSegmentStyle(QLCDNumber::Flat);
        lcdNumber_40 = new QLCDNumber(groupBox_13);
        lcdNumber_40->setObjectName(QStringLiteral("lcdNumber_40"));
        lcdNumber_40->setGeometry(QRect(100, 260, 64, 23));
        lcdNumber_40->setFrameShape(QFrame::NoFrame);
        lcdNumber_40->setSegmentStyle(QLCDNumber::Flat);
        label_56 = new QLabel(groupBox_13);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(10, 171, 81, 21));
        label_29 = new QLabel(groupBox_13);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(10, 80, 81, 17));
        lcdNumber_13 = new QLCDNumber(groupBox_13);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(100, 80, 64, 23));
        lcdNumber_13->setFrameShape(QFrame::NoFrame);
        lcdNumber_13->setFrameShadow(QFrame::Plain);
        lcdNumber_13->setSegmentStyle(QLCDNumber::Flat);
        groupBox_4 = new QGroupBox(centralWidget);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(660, 0, 331, 441));
        groupBox_4->setAlignment(Qt::AlignCenter);
        listView = new QListView(groupBox_4);
        listView->setObjectName(QStringLiteral("listView"));
        listView->setGeometry(QRect(0, 150, 331, 291));
        spinBox = new QSpinBox(groupBox_4);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(190, 40, 71, 33));
        spinBox->setMinimum(1);
        spinBox->setMaximum(200);
        spinBox->setValue(20);
        label_7 = new QLabel(groupBox_4);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(50, 40, 111, 31));
        pushButton_7 = new QPushButton(groupBox_4);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(120, 90, 101, 31));
        groupBox_5 = new QGroupBox(centralWidget);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(0, 440, 531, 501));
        groupBox_5->setAlignment(Qt::AlignCenter);
        listView_2 = new QListView(groupBox_5);
        listView_2->setObjectName(QStringLiteral("listView_2"));
        listView_2->setGeometry(QRect(0, 140, 531, 361));
        pushButton_8 = new QPushButton(groupBox_5);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(320, 90, 91, 27));
        lineEdit_7 = new QLineEdit(groupBox_5);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(270, 40, 31, 23));
        lineEdit_7->setAlignment(Qt::AlignCenter);
        lineEdit_8 = new QLineEdit(groupBox_5);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(100, 70, 201, 23));
        lineEdit_8->setAlignment(Qt::AlignCenter);
        comboBox_3 = new QComboBox(groupBox_5);
        comboBox_3->setObjectName(QStringLiteral("comboBox_3"));
        comboBox_3->setGeometry(QRect(100, 100, 201, 23));
        label_8 = new QLabel(groupBox_5);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 40, 67, 21));
        label_10 = new QLabel(groupBox_5);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 70, 67, 21));
        label_11 = new QLabel(groupBox_5);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 100, 67, 21));
        pushButton_9 = new QPushButton(groupBox_5);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(430, 90, 91, 27));
        lineEdit_6 = new QLineEdit(groupBox_5);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(100, 40, 141, 23));
        lineEdit_6->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(groupBox_5);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(250, 40, 16, 21));
        groupBox_6 = new QGroupBox(groupBox_5);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(320, 30, 201, 51));
        groupBox_6->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(groupBox_6);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 20, 21, 21));
        lineEdit_9 = new QLineEdit(groupBox_6);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(40, 20, 51, 21));
        lineEdit_9->setAlignment(Qt::AlignCenter);
        pushButton_10 = new QPushButton(groupBox_6);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(100, 20, 91, 21));
        groupBox_7 = new QGroupBox(centralWidget);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(530, 440, 711, 501));
        groupBox_7->setAlignment(Qt::AlignCenter);
        listView_3 = new QListView(groupBox_7);
        listView_3->setObjectName(QStringLiteral("listView_3"));
        listView_3->setGeometry(QRect(0, 140, 711, 361));
        label_9 = new QLabel(groupBox_7);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 50, 67, 17));
        label_14 = new QLabel(groupBox_7);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(200, 40, 67, 31));
        label_15 = new QLabel(groupBox_7);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(380, 45, 81, 21));
        label_16 = new QLabel(groupBox_7);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(570, 40, 67, 31));
        spinBox_2 = new QSpinBox(groupBox_7);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setGeometry(QRect(90, 42, 71, 31));
        spinBox_2->setMinimum(0);
        spinBox_2->setMaximum(2000);
        spinBox_2->setValue(30);
        spinBox_4 = new QSpinBox(groupBox_7);
        spinBox_4->setObjectName(QStringLiteral("spinBox_4"));
        spinBox_4->setGeometry(QRect(270, 40, 71, 31));
        spinBox_4->setMinimum(1);
        spinBox_4->setMaximum(2000);
        spinBox_4->setValue(180);
        spinBox_5 = new QSpinBox(groupBox_7);
        spinBox_5->setObjectName(QStringLiteral("spinBox_5"));
        spinBox_5->setGeometry(QRect(470, 40, 71, 31));
        spinBox_5->setMinimum(1);
        spinBox_5->setMaximum(2000);
        spinBox_5->setValue(180);
        spinBox_6 = new QSpinBox(groupBox_7);
        spinBox_6->setObjectName(QStringLiteral("spinBox_6"));
        spinBox_6->setGeometry(QRect(630, 40, 71, 31));
        spinBox_6->setMinimum(1);
        spinBox_6->setMaximum(2000);
        spinBox_6->setValue(240);
        label_25 = new QLabel(groupBox_7);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(250, 100, 91, 20));
        lcdNumber_9 = new QLCDNumber(groupBox_7);
        lcdNumber_9->setObjectName(QStringLiteral("lcdNumber_9"));
        lcdNumber_9->setGeometry(QRect(340, 100, 64, 23));
        lcdNumber_9->setFrameShape(QFrame::NoFrame);
        lcdNumber_9->setSegmentStyle(QLCDNumber::Flat);
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(990, 150, 251, 291));
        groupBox_3->setAlignment(Qt::AlignCenter);
        pushButton_3 = new QPushButton(groupBox_3);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(20, 40, 211, 71));
        pushButton_4 = new QPushButton(groupBox_3);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(20, 120, 211, 71));
        pushButton_5 = new QPushButton(groupBox_3);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(20, 200, 211, 71));
        groupBox_14 = new QGroupBox(centralWidget);
        groupBox_14->setObjectName(QStringLiteral("groupBox_14"));
        groupBox_14->setGeometry(QRect(990, 0, 251, 151));
        groupBox_14->setAlignment(Qt::AlignCenter);
        lineEdit_5 = new QLineEdit(groupBox_14);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(110, 40, 131, 23));
        lineEdit_5->setAlignment(Qt::AlignCenter);
        pushButton_6 = new QPushButton(groupBox_14);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(70, 90, 111, 31));
        label_57 = new QLabel(groupBox_14);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(6, 40, 101, 21));
        Gui->setCentralWidget(centralWidget);

        retranslateUi(Gui);

        QMetaObject::connectSlotsByName(Gui);
    } // setupUi

    void retranslateUi(QMainWindow *Gui)
    {
        Gui->setWindowTitle(QApplication::translate("Gui", "Gui", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("Gui", "Interface 1", Q_NULLPTR));
        label->setText(QApplication::translate("Gui", "Interface", Q_NULLPTR));
        label_2->setText(QApplication::translate("Gui", "IP Address", Q_NULLPTR));
        pushButton->setText(QApplication::translate("Gui", "Set", Q_NULLPTR));
        label_3->setText(QApplication::translate("Gui", "/", Q_NULLPTR));
        checkBox->setText(QApplication::translate("Gui", "Enable RIPv2", Q_NULLPTR));
        groupBox_8->setTitle(QApplication::translate("Gui", "Statistics", Q_NULLPTR));
        groupBox_9->setTitle(QApplication::translate("Gui", "In", Q_NULLPTR));
        label_17->setText(QApplication::translate("Gui", "Ethernet II", Q_NULLPTR));
        label_18->setText(QApplication::translate("Gui", "ARP Request", Q_NULLPTR));
        label_19->setText(QApplication::translate("Gui", "IP", Q_NULLPTR));
        label_20->setText(QApplication::translate("Gui", "ICMP Request", Q_NULLPTR));
        label_21->setText(QApplication::translate("Gui", "UDP", Q_NULLPTR));
        label_22->setText(QApplication::translate("Gui", "RIP Request", Q_NULLPTR));
        label_23->setText(QApplication::translate("Gui", "RIP Response", Q_NULLPTR));
        label_24->setText(QApplication::translate("Gui", "ICMP Reply", Q_NULLPTR));
        label_26->setText(QApplication::translate("Gui", "ARP Reply", Q_NULLPTR));
        groupBox_10->setTitle(QApplication::translate("Gui", "Out", Q_NULLPTR));
        label_33->setText(QApplication::translate("Gui", "Ethernet II", Q_NULLPTR));
        label_34->setText(QApplication::translate("Gui", "ARP Request", Q_NULLPTR));
        label_35->setText(QApplication::translate("Gui", "IP", Q_NULLPTR));
        label_36->setText(QApplication::translate("Gui", "ICMP Request", Q_NULLPTR));
        label_37->setText(QApplication::translate("Gui", "UDP", Q_NULLPTR));
        label_38->setText(QApplication::translate("Gui", "RIP Request", Q_NULLPTR));
        label_39->setText(QApplication::translate("Gui", "RIP Response", Q_NULLPTR));
        label_40->setText(QApplication::translate("Gui", "ICMP Reply", Q_NULLPTR));
        label_27->setText(QApplication::translate("Gui", "ARP Reply", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("Gui", "Interface 2", Q_NULLPTR));
        label_4->setText(QApplication::translate("Gui", "Interface", Q_NULLPTR));
        label_5->setText(QApplication::translate("Gui", "IP Address", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("Gui", "Set", Q_NULLPTR));
        label_12->setText(QApplication::translate("Gui", "/", Q_NULLPTR));
        checkBox_2->setText(QApplication::translate("Gui", "Enable RIPv2", Q_NULLPTR));
        groupBox_11->setTitle(QApplication::translate("Gui", "Statistics", Q_NULLPTR));
        groupBox_12->setTitle(QApplication::translate("Gui", "In", Q_NULLPTR));
        label_41->setText(QApplication::translate("Gui", "Ethernet II", Q_NULLPTR));
        label_42->setText(QApplication::translate("Gui", "ARP Request", Q_NULLPTR));
        label_43->setText(QApplication::translate("Gui", "IP", Q_NULLPTR));
        label_44->setText(QApplication::translate("Gui", "ICMP Request", Q_NULLPTR));
        label_45->setText(QApplication::translate("Gui", "UDP", Q_NULLPTR));
        label_46->setText(QApplication::translate("Gui", "RIP Request", Q_NULLPTR));
        label_47->setText(QApplication::translate("Gui", "RIP Response", Q_NULLPTR));
        label_48->setText(QApplication::translate("Gui", "ICMP Reply", Q_NULLPTR));
        label_28->setText(QApplication::translate("Gui", "ARP Reply", Q_NULLPTR));
        groupBox_13->setTitle(QApplication::translate("Gui", "Out", Q_NULLPTR));
        label_49->setText(QApplication::translate("Gui", "Ethernet II", Q_NULLPTR));
        label_50->setText(QApplication::translate("Gui", "ARP Request", Q_NULLPTR));
        label_51->setText(QApplication::translate("Gui", "IP", Q_NULLPTR));
        label_52->setText(QApplication::translate("Gui", "ICMP Request", Q_NULLPTR));
        label_53->setText(QApplication::translate("Gui", "UDP", Q_NULLPTR));
        label_54->setText(QApplication::translate("Gui", "RIP Request", Q_NULLPTR));
        label_55->setText(QApplication::translate("Gui", "RIP Response", Q_NULLPTR));
        label_56->setText(QApplication::translate("Gui", "ICMP Reply", Q_NULLPTR));
        label_29->setText(QApplication::translate("Gui", "ARP Reply", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("Gui", "ARP table", Q_NULLPTR));
        label_7->setText(QApplication::translate("Gui", "Set ARP timer", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("Gui", "Clear", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("Gui", "Routing table", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("Gui", "Add", Q_NULLPTR));
        label_8->setText(QApplication::translate("Gui", "Network", Q_NULLPTR));
        label_10->setText(QApplication::translate("Gui", "Next Hop", Q_NULLPTR));
        label_11->setText(QApplication::translate("Gui", "Interface", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("Gui", "Clear", Q_NULLPTR));
        label_13->setText(QApplication::translate("Gui", "/", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("Gui", "Delete", Q_NULLPTR));
        label_6->setText(QApplication::translate("Gui", "ID", Q_NULLPTR));
        pushButton_10->setText(QApplication::translate("Gui", "Delete", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("Gui", "RIPv2 database", Q_NULLPTR));
        label_9->setText(QApplication::translate("Gui", "Update", Q_NULLPTR));
        label_14->setText(QApplication::translate("Gui", "Invalid", Q_NULLPTR));
        label_15->setText(QApplication::translate("Gui", "Holddown", Q_NULLPTR));
        label_16->setText(QApplication::translate("Gui", "Flush", Q_NULLPTR));
        label_25->setText(QApplication::translate("Gui", "Update in:", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("Gui", "Controls", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("Gui", "Start", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("Gui", "Stop", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("Gui", "Quit", Q_NULLPTR));
        groupBox_14->setTitle(QApplication::translate("Gui", "Ping", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("Gui", "Ping", Q_NULLPTR));
        label_57->setText(QApplication::translate("Gui", "Destination IP", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class Gui: public Ui_Gui {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GUI_H